### ISSUE TITLE
new patch release for werkzeug 1.0 compatibility

### ISSUE THREAD

**Issue by sblondon** [liuliqiang/flask-theme#12]
Hello, 

could you do a new release (0.3.5?) to fix the import error in Werkzeug 1.0 (https://github.com/liuliqiang/flask-theme/commit/642bf8524666935f174375f057a7238385c5713d)?

Regards

**Comment by liuliqiang** [comment]
Done! @sblondon

**Comment by sblondon** [comment]
Thank you !
