### ISSUE TITLE
ImportError: cannot import name 'contextfunction' from jinja2 (v3.0.0+)

### ISSUE THREAD

**Issue by RogerHaase** [liuliqiang/flask-theme#13]
From https://jinja.palletsprojects.com/en/3.0.x/changes/

"""
The function and filter decorators have been renamed and unified. The old names are deprecated. [#1381](https://github.com/pallets/jinja/issues/1381)

pass_context replaces contextfunction and contextfilter.

pass_eval_context replaces evalcontextfunction and evalcontextfilter

pass_environment replaces environmentfunction and environmentfilter.
"""

Maybe change line 24 from:

    from jinja2 import contextfunction

to:

    from jinja2 import pass_context as contextfunction

**Comment by liuliqiang** [comment]
Hi @RogerHaase , thanks for your information.

Would you like to create a PR for it?

**Comment by RogerHaase** [comment]
Push failed on:

remote: Permission to liuliqiang/flask-theme.git denied to RogerHaase.
fatal: unable to access 'https://github.com/liuliqiang/flask-theme.git/': The requested URL returned error: 403
Pushing to https://github.com/liuliqiang/flask-theme.git

In `flask-theme/__init__.py` line 24 replace:

    from jinja2 import contextfunction

with:

    try:
        from jinja2 import contextfunction
    except ImportError:
        # jinja2 v3.0.0+
        from jinja2 import pass_context as contextfunction

**Comment by liuliqiang** [comment]
Hi @RogerHaase ,

As github's PR, I think you should fork the project, and then push to your fork repo.

Then create a pull request to this repo.
