### ISSUE TITLE
Create new version to enable jinja2>=3.0.0

### ISSUE THREAD

**Issue by UlrichB22** [liuliqiang/flask-theme#15]
Can you please create a new version on Pypi.org with the fix from #13? 
This would help the moinwiki project with issue moinwiki/moin#1109.

Many thanks and kind regards.

**Comment by RogerHaase** [comment]
Hi Liqiang Lau,

Over at moinwiki we are trying to make a moin2 alpha release soon. We need a new Flask-Theme release in the next few days or we will create our own clone on pypi.

Thanks for your work,

Roger Haase

**Comment by liuliqiang** [comment]
hi @RogerHaase , I have release it. 
Thanks for your help!
